const DEFAULT_SEARCH_GIPHY_RESULT_LIMIT = 1
const DEFAULT_SEARCH_GIPHY_OFFSET = 0
const DEFAULT_SEARCH_GIPHY_RATING = 'g'
const DEFAULT_SEARCH_GIPHY_LANG = 'en'
const FALLBACK_GIF_URL = 'https://media0.giphy.com/media/RkJKmVsuPbBXgsrOBh/200.gif?cid=30f29b5f4pvbn3uj0o7mqvypvjqx5xl679ls75bbzzasny61&rid=200.gif'

export {
  DEFAULT_SEARCH_GIPHY_RESULT_LIMIT,
  DEFAULT_SEARCH_GIPHY_OFFSET,
  DEFAULT_SEARCH_GIPHY_RATING,
  DEFAULT_SEARCH_GIPHY_LANG,
  FALLBACK_GIF_URL
}
